name: Compress and Upload Videos

on:
  push:
    paths:
      - "**/*.mp4"
  workflow_dispatch:

jobs:
  compress-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Compress Videos
      run: |
        find . -type f -name '*.mp4' | while read video; do
          base_dir=$(dirname "$video")
          compressed_dir="$base_dir/Compressed"
          mkdir -p "$compressed_dir"
          compressed_video="$compressed_dir/$(basename "$video")"
          
          if [ -f "$compressed_video" ]; then
            echo "Compressed file already exists for $video. Overwriting."
          fi

          ffmpeg -y -i "$video" -vcodec libx264 -crf 28 "$compressed_video"

          if [ ! -f "$compressed_video" ]; then
            echo "Compression failed for $video. Exiting."
            exit 1
          fi
        done

    - name: Check for compressed files
      run: |
        if [[ -z $(find . -type f -name '*.mp4' -path '*/Compressed/*') ]]; then
          echo "No compressed videos found. Exiting."
          exit 1

    - name: Commit compressed videos
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git diff --cached --quiet || git commit -m "chore: compressed new videos"
        git push origin HEAD

    - name: Upload compressed videos as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compressed-videos
        path: '**/Compressed/*.mp4'
        if-no-files-found: warn
