name: Compress and Upload Videos

on:
  push:
    paths:
      - "**/*.mp4"
  workflow_dispatch:

jobs:
  compress-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Determine Compression Scope
      id: compression-scope
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "Compressing only new or modified videos"
          find . -type f -name '*.mp4' -not -path '*/Compressed/*' > files_to_compress.txt
        else
          echo "Manual trigger: Compressing all eligible videos"
          find . -type f -name '*.mp4' -not -path '*/Compressed/*' > files_to_compress.txt
        fi
        echo "::set-output name=files_to_compress::$(cat files_to_compress.txt | xargs)"

    - name: Compress Videos
      if: steps.compression-scope.outputs.files_to_compress != ''
      run: |
        echo "Compressing videos: $(cat files_to_compress.txt)"
        cat files_to_compress.txt | while read video; do
          base_dir=$(dirname "$video")
          compressed_dir="$base_dir/Compressed"
          mkdir -p "$compressed_dir"
          compressed_video="$compressed_dir/$(basename "$video")"
          
          if [ -f "$compressed_video" ]; then
            echo "Compressed file already exists for $video. Skipping."
            continue
          fi

          ffmpeg -y -i "$video" -vcodec libx264 -crf 28 "$compressed_video"

          if [ ! -f "$compressed_video" ]; then
            echo "Compression failed for $video. Exiting."
            exit 1
          fi
        done

    - name: Commit compressed videos
      if: success() && steps['compression-scope'].outputs.files_to_compress != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git diff --cached --quiet || git commit -m "chore: compressed new videos"
        git push origin HEAD

    - name: Upload compressed videos as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compressed-videos
        path: '**/Compressed/*.mp4'
        if-no-files-found: warn
